# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
# url: http://mazhuang.org
date_format: "ordinal"
title: 木公水寿
subtitle: "The record bit by bit, are the mark of my growth"
description: "松涛的个人博客"
keywords: 闵松涛,松涛,SongTao,minsongtao,songtao,PHP,技术博客,linux,闵松涛的博客
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: MinSongTao
organization: zjmedia, Inc.
organization_url: https://www.zjmedia.com
location: Beijing, China
email: 936908163@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: categories

  -
    href: /wiki/
    label: wiki

  -
    href: /links/
    label: links

  -
    href: /about/
    label: about

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: songtaohome/songtaohome.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: songtaohome
# douban_username: freedim
# facebook_username: mzlogin
# weibo_username: mzlogin
# zhihu_username: mzlogin
# twitter_username: mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
#support provider: disqus
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
disqus_username: minsongtao

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [PHP, C, Python, Design Patterns, JavaScrip, Jquery, Linux, CenOS]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
